# .kodiak.toml
version = 1

[merge]

method = "squash"
delete_branch_on_merge = true
require_automerge_label = false

# important
block_on_neutral_required_check_runs = true

# Add useful information & co-authors to the PR commit body
[merge.message]
include_coauthors = true
include_pull_request_author = true
include_pull_request_url = true

