on:
  pull_request_target:

name: Auto Label Bot
jobs:
  jekyll-label-action:
    name: Label
    runs-on: ubuntu-latest
    
    steps:
      - uses: Pandapip1/jekyll-label-action@5fcfb7bef793a76df290f8b491a5529accb7ae46
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: config/.jekyll-labels.yml
