on: [pull_request_target]
name: Auto-Merge Bot
jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: ${{ secrets.TOKEN }}
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        if: ${{!contains( toJson(github), '1272989785' )}}
        uses: ethereum/EIP-Bot@b6cf981087e888b5d7fbd4726458c453f8491532 # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          MERGE_ENABLED: false
