on: [pull_request_target]
name: Auto-Merge Bot
jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: ${{ secrets.TOKEN }}
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: ethereum/EIP-Bot@950d79ddd687f4c78bca2ae49c234d7ebfce0d1f # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          MERGE_ENABLED: false
          CORE_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
          ERC_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
          NETWORKING_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
          INTERFACE_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
          META_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
          INFORMATIONAL_EDITORS: "@MicahZoltu,@lightclient,@arachnid,@cdetrio,@Souptacular,@vbuterin,@nicksavers,@wanderer,@gcolvin,@axic"
