on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'

name: Auto Stagnant Bot
jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: Auto Stagnant Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-stagnant-bot
        uses: ethereum/EIP-Bot@6ca2786b59aff50d83d7060f713af161941c7614 # mark-eips-stale
        id: auto-stagnant-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
