name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  htmlproofer:
    name: HTMLProofer
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@34a865a2b221bd60ec0d4c071f5e7a66ffdac88a
      
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Remove Gemfile.lock
        if: contains(steps.changed-files.outputs.modified_files, 'Gemfile')
        run: rm Gemfile.lock
    
      - name: Install Ruby
        uses: ruby/setup-ruby@08245253a76fa4d1e459b7809579c62bd9eb718a
        with:
          ruby-version: '2.6.0'
          bundler-cache: true
        
      - name: Build Website
        run: |
          bundle exec jekyll doctor
          bundle exec jekyll build
      
      - name: HTML Proofer
        run: bundle exec htmlproofer ./_site --check-html --check-opengraph --report-missing-names --log-level=:debug --assume-extension --empty-alt-ignore --timeframe=6w --disable-external
      
      - name: DNS Validator
        run: bundle exec github-pages health-check
      
      - name: Re-Add Updated Gemfile.lock
        if: contains(steps.changed-files.outputs.modified_files, 'Gemfile') && github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: Gemfile.lock
          commit_message: Re-Add Updated Gemfile.lock
  
  eip-validator:
    name: EIP Validator
    runs-on: ubuntu-latest

    steps:
    - name: Checkout EIP Repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    
    - name: Set Up Rust Toolchain
      uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
      with:
        toolchain: stable
    
    - name: Install EIP Validator
      run: cargo install eipv --version=0.4.0
    
    - name: Run EIP Validator
      run: eipv EIPS/ --ignore=title_max_length,missing_discussions_to --skip=eip-20-token-standard.md

  eipw-validator:
    name: EIPW Validator
    runs-on: ubuntu-latest

    steps:
    - name: Checkout EIP Repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - uses: SamWilsn/eipw-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@2391250ab05295bddd51e36a8c6295edb6343b0e
        with:
          check_filenames: true
          ignore_words_file: .codespell-whitelist
          skip: .git,Gemfile.lock,**/*.png,**/*.gif,**/*.jpg,**/*.svg,.codespell-whitelist,vendor,_site,_config.yml,style.css

