name: Automerge

on:
  pull_request_target:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@a25ea0de41019ad13380d22e01db8f5638f1bcdc
        with:
          token: ${{ secrets.TOKEN }}
          pull-request: ${{ github.event.number }}
