name: Mark stale PRs & Issues

on:
  schedule:
  - cron: 0 0 * * *  # Runs at 00:00 UTC every day.

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Mark Stale Issues
    steps:
    - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
      with:
        # General
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ascending: true # Since we have so many issues, the stale bot finds it hard to keep track. This makes sure that at least the oldest are removed.
        # Issue config
        stale-issue-message: There has been no activity on this issue in three months. It will be closed in a week if no further activity occurs. If you are still pursuing it, feel free to respond to any feedback.
        close-issue-message: This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
        days-before-issue-stale: 90
        days-before-issue-close: 7
        exempt-issue-labels: discussions-to,long-term
        stale-issue-label: stale
        # PR config
        stale-pr-message: There has been no activity on this pull request in two months. It will be closed in a week if no further activity occurs. If you are still pursuing it, feel free to respond to any feedback or request a review in a comment.
        close-pr-message: This pull request was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.
        days-before-pr-stale: 60
        days-before-pr-close: 7
        exempt-pr-labels: long-term
        only-pr-labels: newEIPFile,updateEIP,statusChange
        stale-pr-label: stale
