name: Mark stale PRs & Issues

on:
  schedule:
    - cron: 0 0 * * * # Run this every day

jobs:
  stale:
    name: Mark stale PRs & Issues

    runs-on: ubuntu-latest
    if: github.repository == 'ethereum/eips'

    steps:
    - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        days-before-pr-stale: 60
        days-before-issue-stale: 180
        days-before-pr-close: 7
        days-before-issue-close: 14
        
        exempt-issue-labels: discussions-to
        stale-pr-label: stale
        
        stale-pr-message: There has been no activity on this pull request for two months. It will be closed in a week if no further activity occurs.
        stale-issue-message: There has been no activity on this issue for six months. It will be closed in two weeks if no further activity occurs.

        close-pr-message: This pull request was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.
        close-issue-message: This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.
