name: Vercel Previews

on:
  push:
  pull_request_target:

jobs:
  preview:
    name: Create Preview
    runs-on: ubuntu-latest
    steps:
    - name: Checkout EIP Repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        
    - name: Deploy Preview
      uses: BetaHuhn/deploy-to-vercel-action@f5c4fe753b1c358345ae6794d4dde7df9b37a908
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        ALIAS_DOMAINS: eips--pr-{PR}.now.sh
        PR_PREVIEW_DOMAIN: eips--pr-{PR}.now.sh
        CREATE_COMMENT: true
        DELETE_EXISTING_COMMENT: true
        GITHUB_DEPLOYMENT: false
        DEPLOY_PR_FROM_FORK: true
        PRODUCTION: false
